server:
  port: 7500         #当前服务的端口号
  
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
       defaultZone: http://eurakeserver9000.com:9000/eureka,http://eurakeserver9001.com:9001/eureka,http://eurakeserver9002.com:9002/eureka
  instance: 
    instance-id: woniucloud-provider8002 # 配置注册中心显示出来的微服务名称
    prefer-ip-address: true     #访问路径可以显示IP地址  
    
spring:
  profiles: dev
  application:
    name: woniucloud-config-client-dev
---
server:
  port: 7500         #当前服务的端口号
  
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
       defaultZone: http://eurakeserver9000.com:9000/eureka,http://eurakeserver9001.com:9001/eureka,http://eurakeserver9002.com:9002/eureka
  instance: 
    instance-id: woniucloud-provider8002 # 配置注册中心显示出来的微服务名称
    prefer-ip-address: true     #访问路径可以显示IP地址  
    
spring:
  profiles: test
  application:
    name: woniucloud-config-client-test